// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `encode_jpeg`

/// Decode, resize proportionally to fit within `max_width x max_height`
/// (keeping aspect ratio), encode as JPEG quality 85, return bytes.
Uint8List resizeForUpload({
  required List<int> imageBytes,
  required int maxWidth,
  required int maxHeight,
}) => RustLib.instance.api.crateApiImagingResizeForUpload(
  imageBytes: imageBytes,
  maxWidth: maxWidth,
  maxHeight: maxHeight,
);

/// Resize to `size x size` square (crop to fit), JPEG quality 80.
Uint8List createThumbnail({required List<int> imageBytes, required int size}) =>
    RustLib.instance.api.crateApiImagingCreateThumbnail(
      imageBytes: imageBytes,
      size: size,
    );

/// Remove EXIF metadata by decoding and re-encoding as JPEG (quality 92).
Uint8List stripExif({required List<int> imageBytes}) =>
    RustLib.instance.api.crateApiImagingStripExif(imageBytes: imageBytes);
