// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'nsfw.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

bool validateEmail({required String email}) =>
    RustLib.instance.api.crateApiValidateEmail(email: email);

/// Set the path to the NSFW ONNX model file.
Future<void> loadNsfwModel({required String path}) =>
    RustLib.instance.api.crateApiLoadNsfwModel(path: path);

/// Classify an image as SFW or NSFW.
Future<NsfwResult> nsfwClassify({required List<int> imageBytes}) =>
    RustLib.instance.api.crateApiNsfwClassify(imageBytes: imageBytes);
