// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `load_model`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

/// Set the path to the NSFW ONNX model file.
///
/// Call this at app startup with the path to the bundled model asset,
/// e.g. `loadNsfwModel(path: "assets/models/nsfw.onnx")`.
Future<void> loadNsfwModel({required String path}) =>
    RustLib.instance.api.crateNsfwLoadNsfwModel(path: path);

/// Classify an image as SFW or NSFW.
///
/// `image_bytes` is the raw image data (JPEG, PNG, etc.).
///
/// # Web (WASM)
///
/// tract-onnx does not compile to WASM. On web, this function returns an error
/// instructing the caller to use the platform's JS-based NSFW detection instead.
Future<NsfwResult> nsfwClassify({required List<int> imageBytes}) =>
    RustLib.instance.api.crateNsfwNsfwClassify(imageBytes: imageBytes);

/// NSFW classification result.
class NsfwResult {
  /// 0.0 (safe) to 1.0 (nsfw)
  final double score;
  final bool isNsfw;

  const NsfwResult({required this.score, required this.isNsfw});

  @override
  int get hashCode => score.hashCode ^ isNsfw.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NsfwResult &&
          runtimeType == other.runtimeType &&
          score == other.score &&
          isNsfw == other.isNsfw;
}
