tunnel: 71025a02-45aa-414b-83c0-3dce38eeefcc
credentials-file: /etc/cloudflared/71025a02-45aa-414b-83c0-3dce38eeefcc.json

ingress:
  - hostname: api.turnend.win
    service: http://api:8080
  - service: http_status:404
