// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-qOMAROoTV87LRdjb1oFYPA-nuxB0nNs',
    appId: '1:802311791858:web:189b3370679488f4b5dc6b',
    messagingSenderId: '802311791858',
    projectId: 'foxy-85ecb',
    authDomain: 'foxy-85ecb.firebaseapp.com',
    storageBucket: 'foxy-85ecb.firebasestorage.app',
    measurementId: 'G-9HMYLY0E2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcfSjPtsZ9dlevCskqf1eYSwpLWdvg7Zk',
    appId: '1:802311791858:android:b67bb829ab5505f7b5dc6b',
    messagingSenderId: '802311791858',
    projectId: 'foxy-85ecb',
    storageBucket: 'foxy-85ecb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaXJTHeLeFIMUOVpgaJpSqom1Q2Q-wmI8',
    appId: '1:802311791858:ios:5ef3ea0b88c01541b5dc6b',
    messagingSenderId: '802311791858',
    projectId: 'foxy-85ecb',
    storageBucket: 'foxy-85ecb.firebasestorage.app',
    androidClientId: '802311791858-3e7rs6bgbcr588e10m4k2r1unmc06stv.apps.googleusercontent.com',
    iosClientId: '802311791858-h56q4i2bgdpb49vdsb44g204j86tt17j.apps.googleusercontent.com',
    iosBundleId: 'com.proyectox.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-9DN3Ktpp1NtOEaLvmktO2YWygUg8UBc',
    appId: '1:802311791858:web:9101b92374eec407b5dc6b',
    messagingSenderId: '802311791858',
    projectId: 'foxy-85ecb',
    authDomain: 'foxy-85ecb.firebaseapp.com',
    storageBucket: 'foxy-85ecb.firebasestorage.app',
    measurementId: 'G-69EP4F8TYC',
  );
}
